version: 2.1
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  Node-VB:
     docker: 
        - image: circleci/node:10-browsers
      steps:
       - run:
           name: Rocky
           command: |
           echo 'Vaibhav here'
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Hello-World
     - Node-VB