version : 2
    jobs:
        build:
        - image : apline:3.7
        steps: 
            -run:
                name: The first step
                command: | 
                  echo 'vibhav'
       